development:
    cloudinary_cloud_name: <%= ENV["CLOUDINARY_CLOUD_NAME"] %>
    cloudinary_api_key: <%= ENV["CLOUDINARY_API_KEY"] %>
    cloudinary_api_secret: <%= ENV["CLOUDINARY_API_SECRET"] %>
    news_api_key: <%= ENV["NEWS_API_KEY"] %>
    twitter_consumer_key: <%= ENV["TWITTER_CONSUMER_KEY"] %>
    twitter_consumer_secret: <%= ENV["TWITTER_CONSUMER_SECRET"] %>
    twitter_access_token: <%= ENV["TWITTER_ACCESS_TOKEN"] %>
    twitter_access_token_secret: <%= ENV["TWITTER_ACCESS_TOKEN_SECRET"] %>
    live_scores_api: <%= ENV["LIVE_SCORES_API"] %>
test:
    cloudinary_cloud_name: <%= ENV["CLOUDINARY_CLOUD_NAME"] %>
    cloudinary_api_key: <%= ENV["CLOUDINARY_API_KEY"] %>
    cloudinary_api_secret: <%= ENV["CLOUDINARY_API_SECRET"] %>
    news_api_key: <%= ENV["NEWS_API_KEY"] %>
    twitter_consumer_key: <%= ENV["TWITTER_CONSUMER_KEY"] %>
    twitter_consumer_secret: <%= ENV["TWITTER_CONSUMER_SECRET"] %>
    twitter_access_token: <%= ENV["TWITTER_ACCESS_TOKEN"] %>
    twitter_access_token_secret: <%= ENV["TWITTER_ACCESS_TOKEN_SECRET"] %>
    live_scores_api: <%= ENV["LIVE_SCORES_API"] %>
production:
    cloudinary_cloud_name: <%= ENV["CLOUDINARY_CLOUD_NAME"] %>
    cloudinary_api_key: <%= ENV["CLOUDINARY_API_KEY"] %>
    cloudinary_api_secret: <%= ENV["CLOUDINARY_API_SECRET"] %>
    news_api_key: <%= ENV["NEWS_API_KEY"] %>
    twitter_consumer_key: <%= ENV["TWITTER_CONSUMER_KEY"] %>
    twitter_consumer_secret: <%= ENV["TWITTER_CONSUMER_SECRET"] %>
    twitter_access_token: <%= ENV["TWITTER_ACCESS_TOKEN"] %>
    twitter_access_token_secret: <%= ENV["TWITTER_ACCESS_TOKEN_SECRET"] %>
    live_scores_api: <%= ENV["LIVE_SCORES_API"] %>



    